### PR TITLE
base58 v1.0.0 support

### PR DESCRIPTION
**Pull request by rooterkyberian**
Hi, I would like to use `cashaddress`, but I don't particular like it locking down on base58 version.
It seems that there was a problem with newer one where on Python3 library started returning bytes, not `str` objects, but it was a one line fix.

### CODE REVIEW

**Comment by l0rb** [comment]
Your commit introduces a security issue. It removes the hash-check from base58. Without this you don't know what code you will import and run in the future which possibly could malicious.

**Comment by rooterkyberian** [comment]
When you are installing `cashaddress` package from pypi the hash was not used anyway.
During development you most likely want to reproduce the same process, this is why I changed `requirements.txt` as well.

For a project in which you want to have a reproducible and safe environment, locking down version (and hashing them) make a lot of sense, but if each your dependencies requires a very strict version of other package you will quickly find dependencies clashing preventing you from using you at least one of them.

So it may be that I misunderstood the `requirements.txt` purpose here, i.e. its not for development, but it treats `cashaddress` itself as a standalone project?

**Comment by oskyk** [comment]
I would rather consider native base58 implementation

**Comment by oskyk** [comment]
88180e92f04fe49cf4174d295561f99b598b3318 this should fix the problem

**Pull request closed without merging**
